export const allUnits = {
    availabilityMenu: [
        {
            title: 'Available',
        },
        {
            title: '1 Bedrooms',
        },
        {
            title: '2 Bedrooms',
        },
        {
            title: 'Penthouses',
        }],
    Available: [
        {
            unit: '506',
            bed: "1",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/506.png',
        },
        {
            unit: '705',
            bed: "1",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/705.png',
        },
        {
            unit: '706',
            bed: "2",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/706.png',
        },
        {
            unit: '806',
            bed: "3",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/806.png',
        },
    ],
    oneBedRooms: [
        {
            unit: '506',
            bed: "1",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/506.png',
        },
        {
            unit: '705',
            bed: "1",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/705.png',
        },
    ],
    twoBedRooms: [
        {
            unit: '506',
            bed: "2",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/506.png',
        },
        {
            unit: '705',
            bed: "2",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/705.png',
        },
        {
            unit: '706',
            bed: "2",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/706.png',
        },
    ],
    pentHouses: [
        {
            unit: '506',
            bed: "3",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/506.png',
        },
        {
            unit: '705',
            bed: "3",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/705.png',
        },
        {
            unit: '706',
            bed: "3",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/706.png',
        },
        {
            unit: '806',
            bed: "3",
            bath: "2",
            sqft: 600,
            exposure: "SE",
            price: "890,000",
            cc: "890",
            ret: "890",
            link: 'https://facebook.github.io/react-native/docs/tutorial',
            description: 'Explains a Hello World for React Native.',
            image: '../assets/images/unit_preview/806.png',
        },
    ]
}